function [fitPars,parameters] = ReadParsFile(parsfile)
% fitPars = ReadParsFile(parsfile)
% 
% loads contents of inifile or xmlfile into data structure FitPars
% depending on whether fit method is insightM or DaoSTORM respectively.  
% if no inifile or xmlfile has been loaded yet, load default files.  
%%
global defaultIniFile defaultXmlFile 


[parsFolder,parsName,parsType] = fileparts(parsfile);
parsType = regexprep(parsType,'\.','');

if strcmp(parsName,'ini');
    parsfile = defaultIniFile;
    parsType = 'ini';
elseif strcmp(parsName,'xml');
    parsfile = defaultXmlFile; 
    parsType = 'xml';
end

  % clear fitPars  
if strcmp(parsType,'ini') 
        parameters = {
            'min height=',...
            'max height=',...
            'default background=',...
            'min width=',...
            'max width=',...
            'default width=',...
            'axial ratio tolerance=',...
            'Fit ROI=',...
            'displacement=',...
            'start frame='...
            'allow drift=',...
            'number of molecules in each correlation time step (XY)=',...
            'number of molecules in each correlation time step (Z)=',...
            'minimum time step size (frame)=',...
            'maximum time step size (frame)=',...
            'xy grid size (nm) in xy correlation=',...
            'xy grid size (nm) in z correlation=',...
            'points for moving average in generating drift correlation (XY)=',...
            'points for moving average in generating drift correlation (Z)=',...
            'z method=',...
            'z calibration expression=',...
            'z calibration outlier rejection percentile=',...
            'z calibration start=',...
            'z calibration end=',...
            'z calibration step=',...
            'ROI Valid=',...
            'ROI_x0=',...
            'ROI_x1=',...
            'ROI_y0=',...
            'ROI_y1=',...
            };

        % Get values from loaded inifile
            target_values = read_parameterfile(parsfile,parameters,'');
        % save these values into global FitPars;   
            Pfields = {'minheight','maxheight','bkd','minwidth','maxwidth',...
                'initwidth','maxaxratio','fitROI','displacement','startFrame','CorDrift',...
                'xymols','zmols','minframes','maxframes','xygridxy','xygridz',...
                'movAxy','movAz','Fit3D','zcaltxt','zop','zstart','zend','zstep',...
                'useROI','xmin','xmax','ymin','ymax'};
            fitPars = cell2struct(target_values,Pfields,2);
            
elseif strcmp(parsType,'xml')
    parameters = {
        '<model type="string">',...    method
        '<threshold type="float">'...  threshold
        '<iterations type="int">',...  maxits
        '<baseline type="float">',...   bkd
        '<pixel_size type="float">',... ppnm
        '<sigma type="float">',...      initwidth
        '<descriptor type="string">',... descriptor
        '<radius type="float">',...  displacement
        '<start_frame type="int">',... startFrame
        '<max_frame type="int">',... endFrame
        '<drift_correction type="int">',... %  CorDrift
        '<frame_step type="int">',... dframes
        '<d_scale type="int">',...dscales
        '<do_zfit type="int">',... Fit3D
        '<cutoff type="float">',... zcutoff
        '<min_z type="float">',...  zstart 
        '<max_z type="float">',...  zend
        '<wx_wo type="float">',...  wx0
        '<wx_c type="float">',...  gx
        '<wx_d type="float">',...  zrx
        '<wxA type="float">',...  Ax
        '<wxB type="float">',... Bx
        '<wxC type="float">',...  Cx
        '<wxD type="float">',...  Dx
        '<wy_wo type="float">',...  wy0
        '<wy_c type="float">',...  gy
        '<wy_d type="float">',...  zry
        '<wyA type="float">',...  Ay
        '<wyB type="float">',...  By
        '<wyC type="float">',...  Cy
        '<wyD type="float">',...  Dy
        '<x_start type="int">',... xmin
        '<x_stop type="int">',... xmax
        '<y_start type="int">',... ymin
        '<y_stop type="int">',... ymax
         };
     
    % Read in current parameter values from xmlfile
      target_values = read_parameterfile(parsfile,parameters,'<');
    % save these values into global FitPars;
      Pfields = {'method','threshold','maxits','bkd','ppnm','initwidth',...
          'descriptor','displacement','startFrame','endFrame','CorDrift',...
          'dframes','dscale','Fit3D','zcutoff','zstart','zend','wx0','gx',...
          'zrx','Ax','Bx','Cx','Dx','wy0','gy','zry','Ay','By','Cy','Dy',...
          'xmin','xmax','ymin','ymax'};
      fitPars = cell2struct(target_values,Pfields,2);  
      
end